# SentinelScan - Advanced Process Threat Detector
# Author: Derek Lenz
# Description: This script scans running system processes, detects potentially suspicious ones,
# prints results to the terminal, and generates a PDF report using FPDF.

import datetime                    # Used for timestamping reports
import psutil                      # Library to access system process and hardware info
from fpdf import FPDF, XPos, YPos # FPDF2 is used for PDF report generation

# Whitelisted process names considered safe or critical system processes
WHITELISTED_PROCESSES = {
    "System Idle Process", "csrss.exe", "wininit.exe",
    "lsass.exe", "services.exe", "smss.exe"
}

# Function to determine if a process is suspicious
def is_suspicious(proc):
    try:
        name = proc.name()  # Get process name
        if name in WHITELISTED_PROCESSES:
            return False  # Safe process
        # Flag if not NT AUTHORITY or contains "Unsigned"
        return not proc.username().startswith("NT AUTHORITY") or "Unsigned" in name
    except Exception:
        return True  # Any access error is treated as suspicious

# Start scanning
print("=== SentinelScan: Advanced Process Threat Detector ===")
print("Initializing and scanning running processes. This may take a moment...\n")

# Lists to store process data
processes = []
suspicious_processes = []

# Iterate through all active processes
for proc in psutil.process_iter(['pid', 'name', 'username', 'ppid']):
    try:
        # Attempt to get the parent process name
        parent = psutil.Process(proc.info['ppid']).name() if proc.info['ppid'] else "N/A"

        # Create an entry with basic info and flag status
        entry = {
            "PID": proc.info['pid'],
            "Process Name": proc.info['name'],
            "Username": proc.info['username'] or "N/A",
            "Parent Name": parent,
            "Flags_Display": "Unknown hash, Unsigned binary" if is_suspicious(proc) else "None"
        }

        processes.append(entry)

        # If flagged as suspicious, store in separate list
        if is_suspicious(proc):
            suspicious_processes.append(entry)

    except Exception:
        # Handle access errors gracefully and continue scanning
        continue

# Prepare filenames for report and log
timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
pdf_filename = f"process_scan_report_{timestamp}.pdf"
log_filename = "sentinel_scan.log"

# Print summary report to the screen
print("\n======================================================================")
print("                               SentinelScan Report")
print(f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("======================================================================")
print(f"Total processes scanned: {len(processes)}")
print(f"Suspicious processes detected: {len(suspicious_processes)}\n")

# Print top suspicious processes (up to 10)
print("Top 10 Suspicious Processes:")
headers = ["PID", "Process Name", "Username", "Parent Name", "Flags_Display"]
print(" | ".join(headers))
print("-" * 110)
for proc in suspicious_processes[:10]:
    print(" | ".join(str(proc[h]) for h in headers))

# === PDF Report Generation ===
pdf = FPDF()
pdf.add_page()

# Title section
pdf.set_font("helvetica", "B", 16)
pdf.cell(0, 10, "SentinelScan Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")

# Timestamp
pdf.set_font("helvetica", "", 10)
pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
         new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")

# Summary
pdf.set_font("helvetica", "B", 12)
pdf.cell(0, 10, "Summary:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

pdf.set_font("helvetica", "", 10)
pdf.cell(0, 7, f"Total processes scanned: {len(processes)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 7, f"Suspicious processes detected: {len(suspicious_processes)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

# Table header
pdf.set_font("helvetica", "B", 12)
pdf.cell(0, 10, "Top Suspicious Processes:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

pdf.set_font("helvetica", "", 8)
col_widths = [20, 40, 50, 50, 50]  # Column widths for the table

# Print header row
for i, header in enumerate(headers):
    pdf.cell(col_widths[i], 8, header, border=1, align='C', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
pdf.ln()

# Print process rows (up to 10)
for proc in suspicious_processes[:10]:
    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 6, str(proc[header]), border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln()

# Footer
pdf.set_font("helvetica", "I", 8)
pdf.cell(0, 5, f"Generated by SentinelScan v1.0 on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
         new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="R")

# Save PDF to file
pdf.output(pdf_filename)

# Append basic summary to log file
with open(log_filename, 'a') as log:
    log.write(f"{datetime.datetime.now()} - Scanned {len(processes)} processes. Detected {len(suspicious_processes)} suspicious.\n")

# Final messages
print(f"\nPDF report saved to: {pdf_filename}")
print(f"Detailed logs are available in: {log_filename}")

